# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(default=b'static/app/img/faculty/None/no-img.jpg', upload_to=b'static/app/img/faculty'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ic',
            field=models.ImageField(default=b'static/app/img/teacher/None/no-img.jpg', upload_to=b'static/app/img/teacher'),
        ),
    ]
