# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20151208_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='ic',
            new_name='pic',
        ),
    ]
