# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20151208_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='pic',
            field=models.ImageField(default='static/app/img/faculty/None/no-img.jpg', upload_to='static/app/img/faculty'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default='static/app/img/teacher/None/no-img.jpg', upload_to='static/app/img/teacher'),
        ),
    ]
